---
strategy: polling
no_screen_padding: 'no'
dark_mode: 'no'
static_data: ''
polling_verb: get
polling_url: https://services2.arcgis.com/HdTo6HJqh92wn4D8/arcgis/rest/services/Metro_Nashville_Police_Department_Active_Dispatch_Table_view/FeatureServer/0/query?f=json&cacheHint=true&resultOffset=0&resultRecordCount=50&where=1%3D1&orderByFields=LastUpdated%20ASC%2CObjectId%20ASC&outFields=*&returnGeometry=false&spatialRel=esriSpatialRelIntersects
polling_headers: ''
id: 90541
custom_fields:
- keyname: author_bio
  name: About This Plugin
  field_type: author_bio
  description: Active dispatches for the Metro Nashville Police Department.
  github_url: https://github.com/stephenyeargin/trmnl-mnpd-dispatches
  learn_more_url: https://www.nashville.gov/departments/police/online-resources/active-dispatches
  email_address: stephen@yearg.in
name: Metro Nashville Police Dept. Active Dispatches
refresh_interval: 15
